### ISSUE TITLE
Runtime Exception while starting Dropwizard NewRelicReporter

### ISSUE THREAD

**Issue by Keyurkariya** [newrelic/dropwizard-metrics-newrelic#97]
I am using dropwizard version **0.7.1**, and have added the following dependencies to my build.gradle

```
compile 'com.newrelic.telemetry:dropwizard-metrics-newrelic:0.3.0'
compile 'com.newrelic.telemetry:telemetry-core:0.13.2'
compile 'com.newrelic.telemetry:telemetry-http-okhttp:0.13.2'
```
Have following code to the start of the application
 ```
.............
   @Override
    public void run(AppConfiguration appConfiguration, Environment environment) throws Exception {

        MetricRegistry metricRegistry = new MetricRegistry();
        String apiKey = "<SECRETS>";

        String ingestURI = "<SECRETS>";

        SenderConfiguration senderConfiguration = MetricBatchSender.configurationBuilder()
            .apiKey(apiKey)
            .useLicenseKey(true) // Optional if using a license key instead of an insert key
            .endpoint(URI.create(ingestURI).toURL())
            .httpPoster(new OkHttpPoster(Duration.ofSeconds(2)))
            .build();

        MetricBatchSender metricBatchSender = MetricBatchSender.create(senderConfiguration);

        Attributes commonAttributes = new Attributes()
            .put("host", InetAddress.getLocalHost().getHostAddress())
            .put("appName", "APP Name");

        NewRelicReporter reporter = NewRelicReporter.build(metricRegistry, metricBatchSender)
            .commonAttributes(commonAttributes)
            .build();
        reporter.start(15, TimeUnit.SECONDS);
.............
```

The application build got successful but faced a run time exception with the following stack trace:

```
Exception in thread "main" java.lang.NoSuchMethodError: com.newrelic.telemetry.TelemetryClient.<init>(Lcom/newrelic/telemetry/metrics/MetricBatchSender;Lcom/newrelic/telemetry/spans/SpanBatchSender;)V
	at com.codahale.metrics.newrelic.NewRelicReporterBuilder.build(NewRelicReporterBuilder.java:95)
	at com.org.app_name.Application.run(Application.java:114)
	at com.org.app_name.Application.run(Application.java:41)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
	at io.dropwizard.cli.Cli.run(Cli.java:70)
	at io.dropwizard.Application.run(Application.java:72)
	at com.org.app_name.Application.main(Application.java:45)
```

**Comment by kford-newrelic** [comment]
@Keyurkariya instead of using such an old version of our exporter, could you try using the latest version - `0.7.0` - and see what happens?

**Comment by kford-newrelic** [comment]
@Keyurkariya let us know if this happens with current versions.
